# all available settings of specific linters
linters:
  disable:
    - godot
    - testpackage
    - nakedret
    - funlen
    - noctx
    - gofumpt
    - gocritic
    - paralleltest
    - wrapcheck
    - exhaustivestruct
    - maligned
    - interfacer
    - forbidigo
    - ifshort
    - wastedassign
    - scopelint
    - gci

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - gochecknoglobals

    - path: pkg/hash
      text: "weak cryptographic primitive"
      linters:
        - gosec

    - path: pkg/sfu
      linters:
        - exhaustive
        - gocognit

# all available settings of specific linters
linters-settings:
  cyclop:
    max-complexity: 25