# all available settings of specific linters
linters:
  disable:
    - godot
    - testpackage
    - nakedret
    - funlen
    - noctx
    - gofumpt

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - gochecknoglobals