language: go

go:
  - 1.13.x
  - 1.14.x
  - master

before_install:
  - go get github.com/axw/gocov/...
  - go get github.com/AlekSi/gocov-xml
  - go get -t -v ./...

script:
  - make codecove

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml -v